stages:
  data_ingestion:
    cmd: python src/CnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/CnnClassifier/pipeline/stage_01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images


  prepare_base_model:
    cmd: python src/CnnClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/CnnClassifier/pipeline/stage_02_prepare_base_model.py
      - configs/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src/CnnClassifier/pipeline/stage_03_training.py
    deps:
      - src/CnnClassifier/pipeline/stage_03_training.py
      - src/CnnClassifier/components/prepare_callbacks.py
      - configs/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  

  evaluation:
    cmd: python src/CnnClassifier/pipeline/stage_04_model_evaluation.py
    deps:
      - src/CnnClassifier/pipeline/stage_04_model_evaluation.py
      - configs/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false